-- Copyright (c) 2011-2014, Ailamazyan Program Systems Institute (Russian             
-- Academy of Science). See COPYING in top-level directory.

-- this file is generated by a script; do not edit it
package svnversion is
    constant rev : string := "3769M";
    constant url : string := "https://xoft.ru/svn/skif/t3d-rev05/trunk";
end svnversion;
