INCLUDES = -I../../../../../include -I${master_top_srcdir}/src/include
skifsources = \
 skifch_init.c \
 skifch_work.c \
 skifch_misc.c

lib${MPILIBNAME}_a_SOURCES = ${skifsources}

EXTRA_LIBS = libmpich2-ch3-skif.a
libmpich2-ch3-skif_a_SOURCES = ${skifsources}
